# Content-Type: application/*
CONTENT_JSON = ("Content-Type", "application/json")
CONTENT_XML = ("Content-Type", "application/xml")
CONTENT_PDF = ("Content-Type", "application/pdf")
CONTENT_ZIP = ("Content-Type", "application/zip")
CONTENT_JAVASCRIPT = ("Content-Type", "application/javascript")
CONTENT_OCTET_STREAM = ("Content-Type", "application/octet-stream")
CONTENT_FORM_URLENCODED = ("Content-Type", "application/x-www-form-urlencoded")
CONTENT_LD_JSON = ("Content-Type", "application/ld+json")
CONTENT_SQL = ("Content-Type", "application/sql")
CONTENT_GRAPHQL = ("Content-Type", "application/graphql")
# Content-Type: audio/*
CONTENT_MPEG = ("Content-Type", "audio/mpeg")
CONTENT_WAV = ("Content-Type", "audio/wav")
CONTENT_OGG = ("Content-Type", "audio/ogg")
CONTENT_WEBM = ("Content-Type", "audio/webm")
CONTENT_AAC = ("Content-Type", "audio/aac")
# Content-Type: font/*
CONTENT_WOFF = ("Content-Type", "font/woff")
CONTENT_WOFF2 = ("Content-Type", "font/woff2")
CONTENT_TTF = ("Content-Type", "font/ttf")
CONTENT_OTF = ("Content-Type", "font/otf")
# Content-Type: image/*
CONTENT_JPEG = ("Content-Type", "image/jpeg")
CONTENT_PNG = ("Content-Type", "image/png")
CONTENT_GIF = ("Content-Type", "image/gif")
CONTENT_SVG = ("Content-Type", "image/svg+xml")
CONTENT_WEBP = ("Content-Type", "image/webp")
CONTENT_AVIF = ("Content-Type", "image/avif")
CONTENT_BMP = ("Content-Type", "image/bmp")
CONTENT_TIFF = ("Content-Type", "image/tiff")
# Content-Type: multipart/*
CONTENT_FORM_DATA = ("Content-Type", "multipart/form-data")
CONTENT_BYTERANGES = ("Content-Type", "multipart/byteranges")
CONTENT_MIXED = ("Content-Type", "multipart/mixed")
# Content-Type: text/*
CONTENT_PLAINTEXT = ("Content-Type", "text/plain")
CONTENT_HTML = ("Content-Type", "text/html")
CONTENT_CSS = ("Content-Type", "text/css")
CONTENT_JAVASCRIPT = ("Content-Type", "text/javascript")
CONTENT_CSV = ("Content-Type", "text/csv")
CONTENT_XML = ("Content-Type", "text/xml")
# Content-Type: video/*
CONTENT_MP4 = ("Content-Type", "video/mp4")
CONTENT_MPEG = ("Content-Type", "video/mpeg")
CONTENT_OGG = ("Content-Type", "video/ogg")
CONTENT_WEBM = ("Content-Type", "video/webm")
CONTENT_QUICKTIME = ("Content-Type", "video/quicktime")

# Sec-Fetch-Site
SEC_FETCH_SITE_CROSS_SITE = ("Sec-Fetch-Site", "cross-site")
SEC_FETCH_SITE_SAME_ORIGIN = ("Sec-Fetch-Site", "same-origin")
SEC_FETCH_SITE_SAME_SITE = ("Sec-Fetch-Site", "same-site")
SEC_FETCH_SITE_NONE = ("Sec-Fetch-Site", "none")
